export const Data = {
    status: "success",
    items: [
        {
            id: 1,
            title: "Comida para perros",
            price: 80,
            image: require('./images/producto01.jpg'),
            category: "Comida",
            amount: 1,
        },
        {
            id: 2,
            title: "Arena para gato",
            price: 50,
            image: require('./images/producto02.jpg'),
            category: "Gatos",
            amount: 1,
        },
        {
            id: 3,
            title: "Cama para perros",
            price: 475,
            image: require('./images/producto03.jpg'),
            category: "Perros",
            amount: 1,
        },
        {
            id: 4,
            title: "Casa para gatos",
            price: 1000,
            image: require('./images/producto04.jpg'),
            category: "Gatos",
            amount: 1,
        },
        {
            id: 5,
            title: "Casa para hamster",
            price: 400,
            image: require('./images/producto05.jpg'),
            category: "Jaulas",
            amount: 1,
        },
        {
            id: 6,
            title: "Correa para perros extensible",
            price: 200,
            image: require('./images/producto06.jpg'),
            category: "Perros",
            amount: 1,
        },  
    ],
};